# Generated by Django 4.2.13 on 2024-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
